version: '3.7'
services:
  redis-server:
    image: redis:6-alpine
    restart: always
    env_file:
      - .env.test
    command: "redis-server --appendonly yes"
    ports:
      - "6379:6379"
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOST=redis-server
    ports:
      - "8081:8081"
    depends_on:
      - redis-server
  rpdly-go-uri:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - redis-server